CREATE TABLE IF NOT EXISTS RIDE_INFORMATION (
    RIDE_ID INT AUTO_INCREMENT NOT NULL,
	USER_ID INT NOT NULL,
    ORIGIN VARCHAR(50) NOT NULL,
	DESTINATION VARCHAR(50) NOT NULL,
    DATE_OF_TRAVEL DATE,
    STATUS_INDICATOR CHAR(1) ,
    AVAILABLE_SEATS INT NOT NULL,
    PRIMARY KEY (RIDE_ID)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USER_LOGIN_INFORMATION (
    USER_ID INT AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	SEX CHAR(1) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PHONE_NUMBER VARCHAR(10),
	LAST_LOGIN_DATE DATE,
	RECORD_STATUS CHAR(1) DEFAULT 'A',
	NUMBER_OF_FAILED_ATTEMPTS INT,
	ACCOUNT_DISABLED CHAR(1),
    PRIMARY KEY (USER_ID)
)  ENGINE=INNODB;
